### ISSUE TITLE
State of this incubator

### ISSUE THREAD

**Issue by jonrosner** [vert-x3/vertx-virtual-threads-incubator#12]
I am aware that this is probably not the right place to ask this question, but I cannot ask questions in the Google group for some reason.

I would just like to get some information on what the state of this incubator is. Can we expect to see a production-ready version of this at some point in the (near) future?

For me, the support for virtual threads and a more synchronous way of writing code will probably decide if I will aim to use vert.x or not in future projects. This is why this incubator is so interesting and promising to me.

Thank you very much for your attention!

**Comment by vietj** [comment]
there will be a release of the async/await of the incubator in vertx 4.5 within a few weeks @jonrosner

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vert.x/pull/4835
